### PR TITLE
Fix crash when sweeping values

### PR DESCRIPTION
**Pull request by zenangst**
I had a recurring crash in a client project and managed to trace it back to a class that held an instance `FirebaseRemoteConfig` which is an Objective-C framework. By digging deeper I saw that `sweepValue` ended up crashing with `EXC_BAD_ACCESS`.

```
(lldb) po value
expression produced error: error: Execution was interrupted, reason: EXC_BAD_ACCESS (code=1, address=0x0).
The process has been returned to the state before expression evaluation.
```

I managed to reproduce this and ended up with the following fix, so far I've seen no negative side-effects with the micro-additional work that `sweepValue` needs to do extra.

First cast the value to `AnyObject` then check that the value isn't `nil`.

This one is a bit iffy because we will get a warning stating that this will always succeed.
In our case, we get `Any` from `Mirror` which doesn't give us any clue if the value is present or not. To work around the non-optional, we try and first cast the object and then check the result as trying to cast the underlying object will end up in failing even if the compiler message tells us otherwise.

### CODE REVIEW

**Comment by johnno1962** [comment]
Did you try casting to `AnyObject?`?

**Comment by zenangst** [comment]
@johnno1962 naw forgot about that. Can give it a try now to see how that works.

**Comment by zenangst** [comment]
@johnno1962 you mean like this right:

```swift
guard value as? AnyObject? != nil else { return }
```

**Comment by johnno1962** [comment]
I was just looking at that, but you still get the warning. Could you try:
```
        guard type(of: value) is AnyClass else { return }
```

**Comment by zenangst** [comment]
If we use `AnyClass` instead of `AnyObject` then it never succeeds :/

**Comment by zenangst** [comment]
Seems like a type check won't work in this case, tried changing it to `AnyObject` but I got the same result. The guard always ends up returning early.

**Comment by johnno1962** [comment]
With the type(of: )? Hmmm, out of my depth here.

**Comment by zenangst** [comment]
Yeah I can't get it to pass with `type(of:)` but when I cast and check for `nil` it works.

**Comment by johnno1962** [comment]
🤷‍♂️

**Comment by zenangst** [comment]
I tried this:

image

**Comment by zenangst** [comment]
Nope, didn't work either … should we just roll with what we have here or?

**Comment by johnno1962** [comment]
Let me think about it before we commit something with a warning. Is this a Objc function marked _NotNull returning a nil type of problem perhaps?

**Comment by zenangst** [comment]
@johnno1962 in my case, I think it was this thing that is the cause of the crash:

```objc
+ (nonnull FIRRemoteConfig *)remoteConfig NS_SWIFT_NAME(remoteConfig());
```

**Comment by johnno1962** [comment]
So you fixed it in the end? Be better if the sweep wasn’t crashing in this case tho.

**Comment by zenangst** [comment]
Naw I didn't fix it, I just looked up the mirror key that was causing the crash. Trying to gather more details on what is going on :)

**Comment by johnno1962** [comment]
Thanks for chasing this. I’ve been ankle deep in `Remote` today. It needed a bit of a refresh.

**Comment by zenangst** [comment]
I've been looking into the issue with not being able to inject method signatures that hold default arguments. Basically this old rascal:

```fish
dlopen(/Users/christofferwinterkvist/Library/Containers/com.johnholdsworth.InjectionIII/Data/eval101.dylib, 2): Symbol not found: _$s19ApplicationTarget18TrackingControllerC5track12customAction8category4type5label5value4metaySS_14LogicFramework13CoreAnalyticsV8CategoryOAM9EventTypeOAM5LabelOSiSDyS2SGSgtFfA3_
  Referenced from: /Users/christofferwinterkvist/Library/Containers/com.johnholdsworth.InjectionIII/Data/eval101.dylib
  Expected in: flat namespace
 in /Users/christofferwinterkvist/Library/Containers/com.johnholdsworth.InjectionIII/Data/eval101.dylib ***
```

My best guess with that one is some missing compiler flags when it tries to do the linking of the injected file.

**Comment by johnno1962** [comment]
Not sure there is much you can do about that in the end. It seems to be an implementation detail of the compiler.

**Comment by johnno1962** [comment]
I haven’t had any further thoughts on this but there isn’t any point in merging while there is the warning as the compiler knows best that it will have no effect. I’d like to look at the optional args problem but I can’t get it to not work!

**Comment by zenangst** [comment]
Yeah it feels icky to let this slip in, but I have yet to find another methods that works to fix these kinds of crashes :/

**Comment by johnno1962** [comment]
So it fixed the problem in the end? I hadn’t realised that!

**Pull request merged**
