### PR TITLE
Format README_Chinese markdown document.

### PR DESCRIPTION
**Pull request by raykle**

### CODE REVIEW

**Comment by johnno1962** [comment]
@loohalh what you you make of these changes? @rayke have you used "Standalone injection" where you don't use the app any more. Perhaps it is worth documenting that.

**Comment by raykle** [comment]
@johnno1962 Hi,
Thank you for your comment, I use the "InjectionIII" in almost every app, and every time I come back to read the "README" file, I find the "Chinese" version of README is not good for reading, so I made some Markdown `format` changes, and the contents of it are not changed.

**Comment by raykle** [comment]
ok, the most direct reason that I want to re-format the doc is that the saving file command is `cmd+s`, not the `com+s` which is in the original doc (and appears three times). I think the author of the original Chinese version is not serious.

About the "standalone injection" you mentioned, sorry I haven't tried it yet, but I would like to document it after trying.

**Comment by johnno1962** [comment]
OK Great! Thanks for picking this up. Let me know if "standalone injection" works out for you. It is far simpler to use.

**Comment by johnno1962** [comment]
Hi, have you had a chance to check out using "standalone injection" and update the document? All you need to do is load the bundle but not run the app and it should all work. It's far simpler to document.

**Comment by raykle** [comment]
@johnno1962 Hi,
Yeah, I have tried the "standalone injection", it worked and it's more convenient.

I'll update the PR by adding the introduction of using "standalone injection" later.

**Comment by johnno1962** [comment]
Hi I'm waiting for you to update your PR to mention "standalone injection" then I'll merge. Thanks.

**Comment by raykle** [comment]
@johnno1962 
Hi, sorry for the late PR. 
I have added the doc about 'standalone injection'.

**Comment by johnno1962** [comment]
Thanks for the update, looks good to me. Let me know when you're done pushing and I'll merge.

**Comment by raykle** [comment]
@johnno1962 It's done and ready for merge.

**Comment by johnno1962** [comment]
Merged, Thanks for picking this up!

**Pull request merged**
