### PR TITLE
Update to Retina menu bar icon

### PR DESCRIPTION
**Pull request by ZevEisenberg**
I could also just resize the main app icon to be Retina resolution, but I thought a vector icon would match the Big Sur and above aesthetic better. Happy to change if you prefer.

image

image

Depends on https://github.com/johnno1962/HotReloading/pull/25

### CODE REVIEW

**Comment by johnno1962** [comment]
Hi Zev, Thanks for your PR. I'm rather attached to the existing icon and also think it is worthwhile keeping that it changes colour dependant on the InjectionIII app's state.

**Comment by ZevEisenberg** [comment]
My PR includes color variations, but if I have time I'll look into a more conservative Retina-fying of the existing icon. Thanks for taking the time to look, and for this amazing app!

**Comment by johnno1962** [comment]
Ah, sorry I missed that. Do you know if a PDF inside an Asset catalogue is supported macOS versions back to Mojave? But don't break your back on this. For me, changing the Icon is not a priority.

**Comment by ZevEisenberg** [comment]
Yep, PDFs are supported. And I certainly don't want to take up your time with a change that's not a priority for you. If you'll accept a smaller PR that just increases the resolution of the existing assets, and makes no other changes, I'd love to patch up that paper cut 😉

**Comment by johnno1962** [comment]
Can you avoid using an asset catalogue? They are rather slow to compile and I have limited experience with them.

**Comment by ZevEisenberg** [comment]
Sure thing

**Comment by johnno1962** [comment]
Thanks, but don't spend too much time on this. I can't promise I'll take it on. There is quite quite a testing overhead with menu bar icons.

**Pull request closed without merging**
