### PR TITLE
Update storyboard injection for Xcode 10.2

### PR DESCRIPTION
**Pull request by johnno1962**
HI @zenangst, can you give this a quick test & review. Seems to work for Xcode 10.2. no guarantees for 10.1.

### CODE REVIEW

**Comment by zenangst** [comment]
@johnno1962 took it for a quick spin in Xcode 10.2 but I'm getting this as the output:

```
/bin/bash: line 0: cd: link: No such file or directory
```

**Comment by johnno1962** [comment]
Whoops! Try now.

**Comment by zenangst** [comment]
@johnno1962 that did the trick for Xcode 10.2 👍

**Comment by johnno1962** [comment]
1.5.2?

**Comment by zenangst** [comment]
@johnno1962 on it ;)

**Pull request merged**
