### PR TITLE
Xcode 12 gm

### PR DESCRIPTION
**Pull request by johnno1962**
Hi @zenangst, a couple of changes with a view to producing a release built off the Xcode 12 GM to be merged later this year.

### CODE REVIEW

**Review by zenangst — APPROVED** [review]
👍

**Comment by johnno1962** [comment]
Hi @zenangst, With Big Sur released now, I’m thinking of merging this back onto master. What do you think?

**Comment by zenangst** [comment]
@johnno1962 sounds like a good idea!

**Comment by johnno1962** [comment]
Merged, quite the PR in the end. Originally billed as "a couple of changes" 😂

**Pull request merged**
