### PR TITLE
On device injection.

### PR DESCRIPTION
**Pull request by johnno1962**
There it is, after 5 years since iOS 10 made it "impossible".

### CODE REVIEW

**Review by zenangst — APPROVED** [review]
👏

**Comment by zenangst** [comment]
Haven't gotten to test this out just yet but review-wise it looks good!

**Comment by johnno1962** [comment]
Thanks Chris, no hurry. Still exploring the darker reaches of The Swift package manager…

It works reasonably well despite my not be able to resist refactoring everything.
The enabling package is binary for now as I live in hope that one day injecting 
to the device might be a paid add-on which might solve the “missing business 
model” problem for all this time I’m spending on injection from my wife’s point 
more rational of view. Depends how well it works in the finish I guess.

Downloads continue to be brisk, now more in Europe than in China.

**Comment by orta** [comment]
Nice

**Comment by johnno1962** [comment]
👍 TBH, I never expected it would be possible.

**Pull request merged**
